version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb+srv://golipavansaikrishna2608_db_user:X1WKz2FcBfQLVnbR@cluster0.bvyloaz.mongodb.net/?appName=Cluster0
      - JWT_SECRET=indiamsme2024secretkey
      - FLASK_URL=http://ai-service:8000
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
